name: dart_stl
description: "A package for reading and writing STL files using structures from the vector_math package"
version: 0.0.2
homepage: https://pub.dev

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:


